# Generated by Django 4.0.5 on 2022-07-01 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_item', models.CharField(max_length=50)),
                ('data_adicao', models.DateTimeField(auto_now=True)),
                ('checado', models.BooleanField(default=False)),
            ],
        ),
    ]
